exports.up = knex =>
  knex.schema.createTable('posters', table => {
    table.increments('id')
    table.integer('product_id')
    table.text('description').notNullable()
    // table.text('complement').useNullAsDefault()
    table.text('complement')
    table.text('packaging')
    table.text('price')
    table.boolean('wholesale').defaultTo(false)
    table.text('price_retail')
    table.text('price_wholesale')
    table.timestamp('initial_date')
    table.timestamp('final_date')
    table.integer('user_id').references('id').inTable('users')
    table.integer('campaign_id').references('id').inTable('campaigns')
    table.integer('campaign_type_id').references('id').inTable('campaigns_type')
    table.timestamp('created_at').default(knex.fn.now())
    table.timestamp('updated_at').default(knex.fn.now())
    table.integer('status')
    table.integer('unit')
  })

exports.down = knex => knex.schema.dropTable('posters')
